apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nn7m
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-nn7m@sha256:038a9512bd64bf024385e1c342eb43b7fdd28f5fada35f6426e866f7719de62e
        name: my-nodejs
        resources: {}
status: {}
